# Generated by Django 4.2.8 on 2023-12-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(default='uploads/NoImageFound.png', upload_to='uploads'),
        ),
    ]
