# Generated by Django 4.2.8 on 2023-12-23 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_orderdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='stripe_payment_intent',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='strip_session_id',
            field=models.CharField(default=datetime.datetime(2023, 12, 23, 4, 32, 51, 810295, tzinfo=datetime.timezone.utc), max_length=512),
            preserve_default=False,
        ),
    ]
